-- Create the database if it doesn't exist
CREATE DATABASE IF NOT EXISTS TamilMoviesDB;
USE TamilMoviesDB;

-- Create the movies table with updated column name
CREATE TABLE IF NOT EXISTS movies (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    lead1 VARCHAR(255),  -- Changed column name from 'lead' to 'lead1'
    genre VARCHAR(255),
    director VARCHAR(255),
    rating DECIMAL(3, 1),
    year_of_release INT
);

-- Insert sample movie data with 'lead1' instead of 'lead'
INSERT INTO movies (name, lead1, genre, director, rating, year_of_release) VALUES
('Maara', 'Maadhavan R', 'Love,Adventure', 'Dhilip Kumar', 5.9, 2021),
('Master', 'Vijay', 'Action,Drama', 'Lokesh Kanagaraj', 5.8, 2021),
('Bhoomi', 'Jayam Ravi', 'Social,Drama', 'Laxman', 6.0, 2021),
('Pulikuthi Pandi', 'Vikram Prabhu', 'Crime,Action', 'N R Raghunathan', 5.2, 2021),
('Kabadadaari', 'Sibiraj', 'Crime,Action', 'Pradeep Krishnamoorthy', 6.0, 2021),
('Kalathil Santhippom', 'Arulnidhi', 'Action,Drama', 'N Rajasekar', 5.3, 2021),
('Kutti Story', 'Vijay Sethupathi', 'Love,Romance', 'Gvm', 5.4, 2021),
('Aelay', 'Samuthirakani', 'Comedy,Drama', 'Halitha Shameem', 5.8, 2021),
('Nenjam Marappathillai', 'S J Surya', 'Romance,Horror', 'Selvaraghavan', 5.5, 2021),
('Anbirkiniyal', 'Keertthi Pandiyan', 'Drama,Thriller', 'Gokul', 5.9, 2021),
('Teddy', 'Arya', 'Adventure,Fantasy', 'Sakthi Soundar Rajan', 5.2, 2021),
('Kaadan', 'Vishnu Vishal', 'Adventure,Drama', 'Prabhu Solomon', 5.5, 2021),
('Sulthan', 'Karthik', 'Action,Love', 'Bakkiyaraj Kannan', 5.9, 2021),
('Mandela', 'Yogi Babu', 'Comedy,Drama', 'Madonne Ashwin', 6.6, 2021),
('Karnan', 'Dhanush', 'Action,Drama', 'Maari Selvaraj', 6.8, 2021),
('Jagame Thandhiram', 'Dhanush', 'Action,Drama', 'Karthik Subburaj', 5.0, 2021),
('Vaazhl', 'Pradeep Antony', 'Adventure,Drama', 'Arun Prabu Purushothaman', 5.8, 2021),
('Sarpatta', 'Arya', 'Drama,Sports', 'Pa Ranjith', 7.0, 2021),
('Navarasa', 'Vijay Sethupathi', 'Drama', 'Gvm', 5.6, 2021),
('Netrikann', 'Nayantara', 'Action,Thriller', 'Milind Rau', 5.9, 2021),
('Kasada Tabara', 'Harish Kalyan', 'Fantasy,Drama', 'Chimbu Devan', 6.1, 2021),
('Tughlak Darbar', 'Vijay Sethupathi', 'Comedy,Drama', 'Delhi Prasad Deenadayalan', 5.9,2021),
('Annabelle Sethupathi', 'Vijay Sethupathi', 'Horror,Comedy', 'Deepak Sundarajan', 5.1, 2021),
('Lift', 'Kavin', 'Love,Thriller', 'Vineeth Varaprasad', 5.4, 2021),
('Mugizh', 'Vijay Sethupathi', 'Drama,Family', 'Karthik S', 6.0, 2021),
('Doctor', 'Sivakarthikeyan', 'Comedy,Love', 'Nelson', 6.3, 2021),
('Vinodhaya Sitham', 'Samuthirakani', 'Fantasy,Drama', 'Samuthirakani', 6.0, 2021),
('Oh Manapenney', 'Harish Kalyan', 'Love,Romance', 'Karthik Sundar', 6.0, 2021),
('Jai Bhim', 'Suriya', 'Social,Drama', 'T J Gnanavel', 7.2, 2021),
('Enemy', 'Vishal', 'Action,Drama', 'Anand Shankar', 5.1, 2021),
('Maanaadu', 'Simbu', 'Action,Drama', 'Venkat Prabhu', 6.8, 2021),
('Bachelor', 'Gv Prakash', 'Love,Romance', 'Sathish Selvakumar', 5.6, 2021),
('Writer', 'Samuthirakani', 'Crime,Thriller', 'Franklin Jacob', 6.2, 2021),
('Mahaan', 'Vikram', 'Action, Drama,Thriller', 'Karthik Subbaraj', 7.6, 2022),
('Thiruchitrambalam', 'Dhanush', 'Comedy,Drama, Musical', 'Mithran Jawahar', 7.9, 2022),
('Ponniyin Selvan Part 1', 'Vikram', 'Action,Adventure, Drama', 'Mani Rathnam', 7.6, 2022),
('Jasper','CM Bala','Action,Adventure','yuvaraj D',9.4,2022),
('Beast','vijay','Action','nelson dilipkumar',5.2,2022),
('Valimai','Ajith kumar','Crime,Action','H vinoth',6,2022),
('Love today','Pradeep ranganathan','Comedy,Romance','Pradeep ranganathan',8,2022),
('Etharkkum thunindhavan','suriya','Crime','pandiraj',6.4,2022),
('don','sivakarthikeyan','Comedy','Cibi chakravarthi',6.8,2022),
('cobra','vikram','crime','R Ajay Gnanamuthu',6,2022),
('Vendhu thanindhathu kadu','simbu','crime','Gautham Vasudev menon',7.3,2022),
('sardar','karthi','thriller','PS Mithran',7.5,2022),
('naane varuven', 'dhanush', 'action,horror', 'K selvaraghavan', 6.2, 2022),
('kathuva kulla rendu kadhal', 'vijay sethupathy', 'comedy,drama', 'vignesh shivan', 5.5, 2022),
('mudhal nee mudivum nee', 'kishen das', 'romance', 'darbuka shiva', 7.9, 2022),
('saani kaayidham', 'keerthy suresh', 'thriller', 'arun matheswaran', 7.5, 2022),
('cadaver', 'amala paul', 'crime', 'anoop panicker', 6.5, 2022),
('yaanai', 'arun vijay', 'action,drama', 'hari', 6.1, 2022),
('Prince', 'premji Amaren', 'Action,Drama', 'Anudeep KV', 4.4, 2022),
('Gatta kusthi', 'Vishnu vishal', 'Comedy', 'Chella Ayyavu', 6.5, 2022),
('Maaran', 'Dhanush', 'Action', 'Karthick Naren', 4.4, 2022),
('Viruman', 'Arundhati', 'Action', 'M Muthaiah', 4.9, 2022),
('Nitham Oru Vaanam', 'Abhirami', 'Drama', 'R Karthik', 7.3, 2022),
('Nenjuku Needhi', 'Aari arjunan', 'Crime', 'Arunraja Kamaraj', 7.2, 2022),
('D Block', 'Aashiq', 'Thriller', 'Vijay Kumar Rajendran', 5.5, 2022),
('Captain', 'Arya', 'Scifi,Action', 'Shakti soundar Rajan', 4.4, 2022),
('Dear death', 'santhosh prathap', 'romance, drama', 'prem kumar', 7.7, 2023),
('Vindhya Victim Verdict V3', 'Varalaxmi Sarathkumar', 'thriller, crime', 'amudhavanan', 7.8, 2023),
('thunivu', 'Ajith kumar', 'action, thriller', 'H. Vinoth', 6.1, 2023),
('Varisu', 'Vijay', 'action, thriller', 'Vamshi Paidipally', 6.0, 2023),
('Vallavanukkum Vallavan', 'simha', 'action , comedy', 'vijay tesingu', 7.2, 2023),
('begining', 'vinoth kishan', 'drama, thriller ', 'jagan vijaya', 6.7, 2023),
('Meippada Sei', 'aadhav balaji', 'drama', 'velan', 8.9, 2023),
('Kalathil Vendraal', 'Dharmar Periyasamy', 'action', 'Dharmar Periyasamy', 6.5, 2023),
('run baby run', 'RJ Balaji', 'thriller, drama', 'Jiyen krishna kumar', 5.4, 2023),
('micheal', 'Sundeep kishan', 'action, thriller', 'ranjith jeyakodi', 5.2, 2023),
('dada', 'kavin', 'drama, comedy', 'geanesh k babu', 6.5, 2023),
('vasantha mullai', 'arya', 'thriller, drama', 'Ramanan Purushothama', 4.8, 2023),
('vaathi', 'dhanush', 'action, drama', 'venky alturi', 5.2, 2023),
('The grat indian kitchen', 'aishwarya rajesh', 'drama', 'kannan r', 5.8, 2023),
('ayothi', 'sasikumar m', 'drama', 'mantra moorthy', 6.1, 2023),
('kondraal paavam', 'vetri', 'thriller, drama', 'shyam', 6.0, 2023),
('pathu thala', 'simbu', 'axtion, drama', 'obeil n krishna', 5.7, 2023),
('Viduthai part 1', 'soori', 'crime, drama', 'vetrimaran', 7.1, 2023),
('burqua', 'kalaiyarasan', 'drama', 'sarjun km', 6.0, 2023),
('deiva machan', 'vimal', 'comedy, family', 'martin nirmal kumar', 5.5, 2023),
('yaathisai', 'guru somasundaram', 'action, thriller', 'dharani rasendran', 5.5, 2023),
('ponniyan selvan - part 2', 'vikram', 'history, action', 'mani ratnam', 6.7, 2023),
('good night', 'manikandan', 'comedy, drama', 'vinayak chandrasekaran', 6.2, 2023),
('pichaikaran 2', 'vijay antony', 'action, drama', 'vijay antony', 5.0, 2023),
('kather basha endra muthuramalingam', 'arya', 'romance, drama', 'muthaiya', 5.0, 2023),
('veeran', 'hiphop adhi', 'sci-fi, drama', 'ark saravan', 5.7, 2023),
('por thozhil', 'ashok selvan', 'crime, thriller', 'vignesh raja', 7.1, 2023),
('maamannan', 'vadivelu', 'social, drama', 'maari selvaraj', 7.0, 2023),
('maaveran', 'sivakarthikeyan', 'comedy, drama', 'madonne ashwin', 7.2, 2023),
('DD returns', 'santhanam', 'comedy, horror', 's prem anand', 6.0, 2023),
('jailer', 'rajinikanth', 'action, drama', 'nelson dilipkumar', 6.4, 2023),
('adiyea', 'GV prakash', 'sci-fi, romance', 'vignesh karthick', 5.5, 2023),
('mark antony', 'SJ surya', 'sci-fi, thriller', 'adhik ravichandran', 5.8, 2023),
('chandramukhi 2', 'raghava lawrence', 'thriller, horror', 'vasu p', 3.3, 2023),
('chithha', 'siddharth narayan', 'drama, family', 'su arunkumar', 7.0, 2023),
('leo', 'vijay', 'action, drama', 'lokesh kanagaraj', 6.4, 2023),
('Jigardhanda double X', 'raghava lawrence', 'comedy, drama', 'karthik subburaj', 6.8, 2023),
('japan', 'karthik sivakumar', 'mystry, drama', 'rajamurugan', 4.2, 2023),
('joe', 'rioraj', 'romance, love', 'hariharan ram', 5.0, 2023),
('parking', 'harish kalyan', 'thriller, drama', 'ramkumar balakrishnan', 6.1, 2023),
('Annapoorni', 'nayantara', 'drama', 'nilesh krishnaa', 5.5, 2023),
('fight club', 'vijayakumar', 'action, drama', 'abbas rahmath', 5.9, 2023),
('saba nayagan', 'ashok selvan', 'comedy, romance', 'CS karthikeyan', 6.0, 2023),
('Ayalaan', 'Sivakarthikeyan', 'sci-fi, drama', 'R Ravikumar', 6.0, 2024),
('captain miller', 'dhanush', 'action, drama', 'arun matheswaran', 6.8, 2024),
('Singapore saloon', 'RJ balaji', 'drama', 'gokul', 5.2, 2024),
('blue star', 'ashok selvan', 'sports, drama', 'santhosh P narayanan', 6.4, 2024),
('vadakkupatti ramasamy', 'santhanam', 'comedy, drama', 'karthik yogi', 5.3, 2024),
('lal salaam', 'vishnu vishal', 'social, action', 'aishwarya dhanush', 5.3, 2024),
('lover', 'Manikandan', 'Romance, drama', 'Prabhuram vyas', 6.9, 2024),
('siren', 'jayam ravi', 'action, thriller', 'antony bhagyaraj', 4.3, 2024),
('rebel', 'gv prakash', 'action, drama', 'nikesh rs', 6.0, 2024),
('kalvan', 'gv prakash', 'adventure, drama', 'pv shankar', 4.0, 2024),
('dear', 'gv prakash', 'family, drama', 'anand ravichandran ', 4.8, 2024),
('romeo', 'vijay antony', 'comedy, drama', 'vinayak vaithianathan', 6.2, 2024),
('ratham', 'vishal', 'action, drama', 'hari', 4.3, 2024),
('kurangu pedal', '(none)', 'comedy, family', 'kamalakannan', 6.0, 2024),
('aranmanai 4', 'tamannah bhatia', 'horror, thriller', 'sundar c ', 4.3, 2024),
('star', 'kavin', 'romance, drama', 'elan', 5.5, 2024),
('ptsir', 'hiphop adhi', 'comedy, drama', 'karthik venugopalan', 4.9, 2024),
('garudan', 'soori', 'action, drama', 'RS durai senthilkumar', 7.1, 2024),
('maharaja', 'viajay sethupathi', 'action, drama', 'nithilan', 8.1, 2024),
('indian 2', 'kamal haasan', 'action, social', 'shankar s', 3.3, 2024),
('raayan', 'dhanush', 'action, thriller', 'dhanush', 6.5, 2024),
('pechi', 'bala saravanan', 'horror, thriller', 'mg ramachandran', 5.1, 2024),
('demonty colony 2', 'arulnidhi', 'thriller, horror', 'ajay gnanamuthu', 5.5, 2024),
('thangalaan', 'vikram', 'action', 'pa ranjith', 6.0, 2024),
('vaazhai', '(none)', 'Drama, social', 'maari selvaraj', 9.2, 2024),
('The greatest of all time', 'vijay', 'sci-fi, action', 'venkat prabhu', 4.3, 2024),
('kadaisi ulaga por', 'hiphop adhi', 'action, drama', 'himhop adhi', 5.7, 2024),
('lubber pandhu', 'harish kalyan', 'sports, drama', 'tamizharasan pachaimuthu', 8.0, 2024),
('meiyazhagan', 'karthik sivakumar', 'family, drama', 'c prem kumar', 7.8, 2024),
('hitler', 'vijay antony', 'action, thriller', 'dhana', 4.5, 2024),
('vettaiyan', 'rajinikanth', 'action, drama', 'tj gnanavel', 6.4, 2024),
('amaran', 'sivakarthikeyan', 'action, romance', 'rajkumar periyasamy', 8.5, 2024),
('brother', 'jayam ravi', 'romance, comedy', 'rajesh m', 5.0, 2024),
('bloody beggar', 'kavin', 'comedy, drama', 'sivabalan muthukumar', 4.9, 2024),
('sir', 'vimal', 'drama, thriller', 'bose venkat', 4.2, 2024),
('Darbar', 'Rajinikanth', 'Action, Drama', 'Murugadoss A R', 5.6, 2020),
('Pattas', 'Dhanush', 'Action, Fantasy', 'Durai Senthilkumar R S', 5.3, 2020),
('Psycho', 'Udhayanidhi Stalin', 'Thriller, Crime', 'Myshkin', 6.0, 2020),
('Naadodigal 2', 'Sasikumar', 'Drama, Love', 'Samuthirakani', 5.2, 2020),
('Vaanam Kottattum', 'Vikram Prabhu', 'Actioin, Drama', 'Dhana', 5.8, 2020),
('Seeruu', 'Jiiva', 'Action, thriller', 'Rathna Shiva', 5.3, 2020),
('Oh My Kadavule', 'Ashok Selvan', 'Love, Romance', 'Ashwath Marimuthu', 6.4, 2020),
('Naan Sirithal', 'Hiphop Adhi', 'Comedy, Drama', 'Raana', 5.4, 2020),
('Kamali From Nadukaveri', 'Anandhi', 'Drama, Love', 'Rajasekar Duraisamy', 5.9, 2020),
('Mafia', 'Arun Vijay', 'Action, Thriller', 'Karthick Naren', 5.6, 2020),
('Kannum Kannum Kollai Adithaal', 'Dulquer Salman', 'Love, Romance', 'Desingh Periasamy', 6.3, 2020),
('Gypsy', 'Jiiva', 'Comedy, Drama', 'Rajumurugan', 5.6, 2020),
('Asuraguru', 'Vikram Prabhu', 'Action, Thriller', 'Rajdeep', 5.1, 2020),
('Dharala prabhu', 'Harish Kalyan', 'Comedy, Romance', 'Krishna Marimuthu', 6.1, 2020),
('Ponmagal Vandhal', 'Jyothika', 'Thriller, Crime', 'Jj Fredrick', 5.0, 2020),
('Penguin', 'Keerthi Suresh', 'Drama, Mystery', 'Eashvar Karthic', 5.5, 2020),
('Oru Pakka Kadhai', 'Kalidas Jayaram', 'Love, Romance', 'Balaji Tharaneetharan', 5.8, 2020),
('Ka Pae Ranasingam', 'Vijay Sethupathi', 'Social, Drama', 'Virumandi', 5.8, 2020),
('Varma', 'Dhruv Vikram', 'Love, Romance', 'Bala', 5.4, 2020),
('Putham Pudhu Kaalai', 'Kalidas Jayaram', 'Drama, Love', 'Suhashini Maniratnam', 6.0, 2020),
('Soorarai Pottru', 'Suriya', 'Biography, Drama', 'Sudha Kongara', 7.2, 2020),
('Mookuthi Amman', 'Nayantara', 'comedy, Fantasy', 'R J Balaji', 6.0, 2020),
('Andhaghaaram', 'Arjun Das', 'Mystery, Thriller', 'V Vignarajan', 5.9, 2020),
('Triples', 'Jai', 'Comedy, Drama', 'Charukesh', 5.0, 2020),
('Paava Kadhaigal', 'Sai Pallavi', 'Drama, Comedy', 'Gvm', 6.2, 2020),
('Sketch', 'Vikram', 'Action, Drama', 'Vijay Chandar', 5.0, 2018),
('Gulebagavali', 'Prabhudeva', 'Action, Comedy', 'Kalyaan', 5.2, 2018),
('Thaana Serndha Kootam', 'Suriya', 'Action, Comedy', 'Vignesh Shivan', 5.9, 2018),
('Padmaavat', 'Deepika Padukone', 'Romance, classics', 'Sanjay Leela', 6.6, 2018),
('Bhaagamathie', 'Anushka Shetty', 'Thriller, Horror', 'G. Ashok', 5.6, 2018),
('Mannar Vagaiyara', 'Vimal', 'Comedy, Love', 'Boopathy Pandian', 5.0, 2018),
('Nimir', 'Udhayanidhi Stalin', 'Comedy, Love', 'Priyadarsan', 5.3, 2018),
('Madurai Veeran', 'Samuthirakani', 'Action, Drama', 'p G Muthaiah', 5.7, 2018),
('Kalakalappu 2', 'Jiiva', 'Comedy, Drama', 'Sundar C', 5.4, 2018),
('Naachiyar', 'Jyothika', 'Crime,Thriller', 'Bala', 6.0, 2018),
('Naghesh Thiraiyarangam', 'Aari', 'Horror, Drama', 'Isaq', 4.0, 2018),
('Diya', 'Sai Pallavi', 'Horror, Thriller', 'Vijay A I', 55.2, 2018),
('Irumbu Thirai', 'Vishal', 'Action, Thriller', 'P S Mithran', 6.3, 2018),
('Iravukku Aayiram Kangal', 'Arulnidhi', 'Crime, Thriller', 'Mu. Maran', 6.0, 2018),
('Nadigaiyar Thilagam', 'Dulquer Salman', 'Biography, Drama', 'Nag Ashwin', 6.8, 2018),
('Bhaskar Oru Rascal', 'Arvind Swamy', 'Comedy, action', 'Siddique', 4.7, 2018),
('Oru Kuppai Kadhai', 'Yogi Babu', 'Love, Drama', 'Kaali Rangasamy', 5.4, 2018),
('Sema', 'Gv Prakash', 'COmedy, Love', 'Vallikanth', 5.4, 2018),
('Kaala', 'Rajinikanth', 'Action, drama', 'PA Ranjith', 6.5, 2018),
('Goli Soda 2', 'Samuthirakani', 'Action,Drama', 'S D Vijay Milton', 5.3, 2018),
('Tik Tik Tik', 'Jayam Ravi', 'Thriller, Sci-Fi', 'Shakthi Soundar Rajan', 5.5, 2018),
('Asuravadham', 'Sasikumar', 'Action, Drama', 'Maruthupandian', 5.9, 2018),
('Tamizh Padam 2', 'Shiva', 'Comedy, Parody', 'Amudan. C. S', 5.5, 2018),
('Kadai Kutty Singam', 'Karthik', 'Family, Action', 'Pandiaraj', 5.9, 2018),
('Junga', 'Vijay Sethupathi', 'Comedy, Drama', 'Gokul', 5.0, 2018),
('Ghajinikanth', 'Arya', 'Comedy, Drama', 'Santhosh P.Jayakumar', 5.3, 2018),
('Pyaar Prema Kaadhal', 'Harish Kalyan', 'Romance, Love', 'Elan', 6.1, 2018),
('Vishwaroopam 2', 'Kamal Haasan', 'Thriller, Crime', 'Kamal Haasan', 5.4, 2018),
('Kolamavu Kokila', 'Nayantara', 'Comedy, Drama', 'Nelson Dhilipkumar', 6.3, 2018),
('Lakshmi', 'Prabhudeva', 'Drama, Children', 'Vijay A I', 5.2, 2018),
('Imaikkaa Nodigal', 'Adharvaa Murali', 'Romance, Thriller', 'Ajay Gnanamuthu', 6.0, 2018),
('60 Vayadhu Maaniram', 'Prakash Raj', 'Thriller, Drama', 'Radhamohan', 6.0, 2018),
('U Turn', 'Samantha Ruthprabhu', 'Mystery, Thriller', 'Pawan Kumar', 6.2, 2018),
('Seema Raja', 'Sivakarthikeyan', 'Action, Comedy', 'Ponram', 4.4, 2018),
('Saamy 2', 'Vikram', 'Action, Love', 'Hari', 5.0, 2018),
('Chekka Chivantha Vaanam', 'Simbu', 'Action, Drama', 'Mani Rathnam', 6.7, 2018),
('96', 'Vijay Sethupathi', 'Love, Romance', 'C Prem Kumar', 7.3, 2018),
('Raatchasan', 'Vishnu Vishal', 'Thriller, Crime', 'Ram Kumar', 7.9, 2018),
('Nota', 'Vijay Devarkonda', 'Thriller, Drama', 'Anand Shankar', 5.3, 2018),
('Vada Chennai', 'Dhanush', 'Action, Drama', 'Vetrimaaran', 7.4, 2018),
('Sandakozhi 2', 'Vishal', 'Action, Drama', 'Lingusamy', 5.0, 2018),
('Sarkar', 'Vijay', 'Actioin, Thriller', 'Murugadoss A R', 5.7, 2018),
('Thimiru Pudichavan', 'Vijay Antony', 'Action, Drama', 'Ganeshaa', 5.0, 2018),
('Kaatrin Mozhi', 'Jyotika', 'Family, Love', 'Radhamohan', 6.0, 2018),
('2.O', 'Rajinikanth', 'Sci-Fi, Adventure', 'Shanker S', 6.9, 2018),
('Kanaa', 'Sathyaraj', 'Sports, Drama', 'Arunraja Kamaraj', 6.2, 2018),
('Maari 2', 'Dhanush', 'Action, Drama', 'Balaji Mohan', 5.3, 2018),
('Adanga Maru', 'Jayam Ravi', 'Action, Drama', 'Karthik Thangavel', 6.0, 2018),
('bairavaa', 'vijay', 'action, drama', 'bharathan', 4.7, 2017),
('bogan', 'jayam ravi', 'thriller, fantasy', 'lakshman', 6.1, 2017),
('singham 3', 'suriya sivakumar', 'action, drama', 'hari', 5.2, 2017),
('yeman', 'vijay antony', 'thriller, action', 'jeeva sankar', 5.5, 2017),
('yakkai', 'kreshna', 'romance, thriller', 'kulandai vellappan', 4.1, 2017),
('kuttram 23', 'arun vijay', 'action, thriller', 'arivazhagan', 6.2, 2017),
('motta siva ketta siva', 'raghava lawrence', 'action, horror', 'raghava lawrence', 3.7, 2017),
('maanagaram', 'regina cassandra', 'thriller, drama', 'lokesh kanagaraj', 7.4, 2017),
('baloon', 'jai', 'horror, drama', 'sinish', 5.0, 2017),
('velaikkaran', 'sivakarthikeyan', 'action, thriller', 'mohan raja', 6.2, 2017),
('sakka podu podu raja', 'santhanam', 'comedy, drama', 'sethuraman', 3.4, 2017),
('aruvi', 'aditi balan', 'social, drama', 'arun prabu purushothaman', 8.0, 2017),
('sathya', 'sibiraj', 'crime, thriller', 'pradeep kirishnamoorthy', 6.1, 2017),
('dora', 'nayantara', 'thriller, horror', 'dass ramasamy', 4.4, 2017),
('bruce lee', 'gv prakash', 'comedy,drama', 'prashanth pandiyaraj', 2.7, 2017),
('richie', 'nivin pauly', 'action, drama', 'gautham ramachandran', 5.4, 2017),
('kodi veeran', 'sasikumar m', 'action, family', 'muthaiah M', 4.6, 2017),
('annadurai', 'vijay antony', 'action, thriller', 'g srinivasan', 5.1, 2017),
('theeran athigaram ondru ', 'karthik sivakumar', 'action, thriller', 'h vinoth', 7.8, 2017),
('aramm', 'nayantara', 'social, drama', 'gopi nainar', 7.8, 2017),
('ippadai vellum', 'udhayanidhi stalin', 'comedy, action', 'gaurav narayanan', 5.4, 2017),
('aval', 'siddharth narayanan', 'horror, thriller', 'milind rao', 6.6, 2017),
('mersal', 'vijay', 'action, drama', 'atlee', 7.8, 2017),
('chennaiyil oru naal 2', 'sarath kumar r', 'crime, thriller', 'jpr', 3.8, 2017),
('solo', 'dulquer salman', 'romance, thriller', 'bejoy Nambiar', 6.2, 2017),
('hara hara mahadevaki', 'gautham karthik', 'comedy, drama', 'saravanan m', 4.8, 2017),
('karuppan', 'vijay sethupathi', 'action, drama', 'paneerselvam', 5.4, 2017),
('spyder', 'mahesh babu', 'thriller, crime', 'murugadoss ar', 6.2, 2017),
('magalir mattum', 'jyotika saravanan', 'drama', 'bramma g', 6.1, 2017),
('thupparivalan', 'vishal ', 'crime, drama', 'myshkin', 6.8, 2017),
('kurangu bommai', 'vidharth', 'drama, crime', 'nithilan', 6.6, 2017),
('puriyadha pudhir', 'vijay sethupathi', 'love,drama', 'ranjith jeyakodi', 5.6, 2017),
('vivegam', 'ajith kumar', 'action,drama', 'siva', 5.5, 2017),
('velai illa pattadhari 2', 'dhanush', 'action, comedy', 'soundarya rajinikanth', 5.2, 2017),
('meesaya murukku', 'hiphop adhi', 'romace, comedy', 'hiphop adhi', 5.5, 2017),
('vikram vedha', 'vijay sethupathi', 'crime, thriller', 'pushkar gayathri', 7.4, 2017),
('gemini Ganeshanum Suruli Raajanum', 'adharvaa murali', 'comedy, drama', 'odam ilavarasu', 5.2, 2017),
('vanamagan', 'jayam ravi', 'adeventure, drama', 'vijay ai', 5.4, 2017),
('maragadha nanayam', 'aadhi', 'comedy, fantasy', 'ark saravanan', 5.9, 2017),
('sathiyan', 'vikram prabhu', 'action, drama', 'SR prabhakaran', 4.2, 2017),
('rangoon', 'gautham karthik', 'action, thriller', 'rajkumar periyasamy', 6.3, 2017),
('Saravanan Irukka Bayamaen', 'udhayanidhi stalin', 'love, comedy', 'ezhil s', 3.1, 2017),
('bahubali 2', 'prabhas', 'adventure, war', 'SS rajamouli', 7.6, 2017),
('pa paandi', 'rajkiran', 'action, drama', 'dhanush', 6.8, 2017),
('shivalinga', 'raghava lawrence', 'horror, thriller', 'vasu p', 4.8, 2017),
('kaatru veliyidai','Karthik sivakumar','romance, love','mani ratnam', 5.8, 2017),
('kavan ', 'vijay sethupathi', 'action, thriller', 'KV anand', 6.8, 2017);

-- Verify the records inserted
SELECT count(*) FROM movies;








